-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 12:36:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CATEGORIAS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIAS` (
  `id_categoria` INT NOT NULL,
  `nome_categoria` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOADORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOADORES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOADORES` (
  `id_doador` INT NOT NULL,
  `nome_doador` VARCHAR(45) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(45) NULL DEFAULT NULL,
  `Rua` VARCHAR(45) NULL DEFAULT NULL,
  `Bairro` VARCHAR(45) NULL DEFAULT NULL,
  `CEP` INT(8) NULL DEFAULT NULL,
  `Numero` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `data_ultima_doacao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_doador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUTOS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTOS` (
  `id_produto` INT NOT NULL,
  `nome_produto` VARCHAR(45) NULL DEFAULT NULL,
  `Valor` FLOAT NULL DEFAULT NULL,
  `Quantidade` INT NULL DEFAULT NULL,
  `CATEGORIAS_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  CONSTRAINT `fk_PRODUTOS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_id_categoria`)
    REFERENCES `mydb`.`CATEGORIAS` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PRODUTOS_CATEGORIAS1` ON `mydb`.`PRODUTOS` (`CATEGORIAS_id_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`funcionário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`funcionário` ;

CREATE TABLE IF NOT EXISTS `mydb`.`funcionário` (
  `idfuncionário` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `data_entrada` DATE NULL,
  `telefone` CHAR(11) NULL,
  PRIMARY KEY (`idfuncionário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`criança acolhida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`criança acolhida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`criança acolhida` (
  `id_crianca` INT NOT NULL,
  `grauparalisia` INT NULL,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `funcionário_idfuncionário` INT NOT NULL,
  PRIMARY KEY (`id_crianca`),
  CONSTRAINT `fk_criança acolhida_funcionário1`
    FOREIGN KEY (`funcionário_idfuncionário`)
    REFERENCES `mydb`.`funcionário` (`idfuncionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_criança acolhida_funcionário1_idx` ON `mydb`.`criança acolhida` (`funcionário_idfuncionário` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`instituições _parceiras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instituições _parceiras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instituições _parceiras` (
  `id_instituicao` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  PRIMARY KEY (`id_instituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOACOES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOACOES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOACOES` (
  `id_doacoes` INT NOT NULL,
  `Valor` FLOAT NULL DEFAULT NULL,
  `Quantidade` INT NULL DEFAULT NULL,
  `DOADORES_id_doador` INT NOT NULL,
  `PRODUTOS_id_produto` INT NOT NULL,
  `CATEGORIAS_id_categoria` INT NOT NULL,
  `funcionário_idfuncionário` INT NOT NULL,
  `criança acolhida_id_crianca` INT NOT NULL,
  `instituições _parceiras_id_instituicao` INT NOT NULL,
  PRIMARY KEY (`id_doacoes`),
  CONSTRAINT `fk_DOACOES_DOADORES1`
    FOREIGN KEY (`DOADORES_id_doador`)
    REFERENCES `mydb`.`DOADORES` (`id_doador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOACOES_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_id_produto`)
    REFERENCES `mydb`.`PRODUTOS` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOACOES_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_id_categoria`)
    REFERENCES `mydb`.`CATEGORIAS` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOACOES_funcionário1`
    FOREIGN KEY (`funcionário_idfuncionário`)
    REFERENCES `mydb`.`funcionário` (`idfuncionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOACOES_criança acolhida1`
    FOREIGN KEY (`criança acolhida_id_crianca`)
    REFERENCES `mydb`.`criança acolhida` (`id_crianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOACOES_instituições _parceiras1`
    FOREIGN KEY (`instituições _parceiras_id_instituicao`)
    REFERENCES `mydb`.`instituições _parceiras` (`id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DOACOES_DOADORES1` ON `mydb`.`DOACOES` (`DOADORES_id_doador` ASC) VISIBLE;

CREATE INDEX `fk_DOACOES_PRODUTOS1` ON `mydb`.`DOACOES` (`PRODUTOS_id_produto` ASC) VISIBLE;

CREATE INDEX `fk_DOACOES_CATEGORIAS1` ON `mydb`.`DOACOES` (`CATEGORIAS_id_categoria` ASC) VISIBLE;

CREATE INDEX `fk_DOACOES_funcionário1_idx` ON `mydb`.`DOACOES` (`funcionário_idfuncionário` ASC) VISIBLE;

CREATE INDEX `fk_DOACOES_criança acolhida1_idx` ON `mydb`.`DOACOES` (`criança acolhida_id_crianca` ASC) VISIBLE;

CREATE INDEX `fk_DOACOES_instituições _parceiras1_idx` ON `mydb`.`DOACOES` (`instituições _parceiras_id_instituicao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`TELEFONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TELEFONE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TELEFONE` (
  `telefone_fixo` BIGINT(14) NULL DEFAULT NULL,
  `celular` BIGINT(14) NULL DEFAULT NULL,
  `DOADORES_id_doador` INT NOT NULL,
  CONSTRAINT `fk_TELEFONE_DOADORES1`
    FOREIGN KEY (`DOADORES_id_doador`)
    REFERENCES `mydb`.`DOADORES` (`id_doador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TELEFONE_DOADORES1` ON `mydb`.`TELEFONE` (`DOADORES_id_doador` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
